axi/axi_full_to_half_duplex.v
axi/axi_interconnect_beta/arbiter.v
axi/axi_interconnect_beta/axi_interconnect_beta.sv
axi/axi_interconnect_beta/axi_rdata_sfifo.v
axi/axi_interconnect_beta/axi_wdata_sfifo.v
axi/axi_interconnect_beta/crossbar.v
axi/axi_interconnect_beta/fixed_priority_arbiter.v
axi/axi_interconnect_beta/lb_to_axi.v
axi/axi_interconnect_beta/master_coupler.v
axi/axi_interconnect_beta/round_robin_priority_arbiter.v
axi/axi_interconnect_beta/slave_coupler.v
axi/axi_interconnect_beta/slave_coupler_wrapper.v
cam/cam_crop.v
cam/cam_csi_rx_controllers.v
cam/cam_line_buffer.v
cam/cam_picam.v
cam/cam_raw_to_rgb.v
cam/cam_rgb2gray.v
cam/cam_rgb_gain.v
cam/cam_scale_down_2x_nn.v
cam/cam_scale_up_2x_nn.v
common/common_apb3.v
common/common_efx_fifo_wrapper.v
common/common_reset.v
common/common_reset_ctrl.v
common/common_shift_reg.v
common/common_simple_dual_port_ram.v
common/common_true_dual_port_ram.v
common/common_ti180_ddr_config.sv
display/hdmi/display_hdmi_adv7511_config.v
display/hdmi/display_hdmi_color_coding_converter.v
display/hdmi/display_hdmi_data_unpack.v
display/hdmi/display_hdmi_dual_clock_fifo.v
display/hdmi/display_hdmi_i2c_phy.v
display/hdmi/display_hdmi_i2c_wrapper.v
display/hdmi/display_hdmi_rgb_to_yuv.sv
display/hdmi/display_hdmi_vga_gen_v2.v
display/hdmi/display_hdmi_yuv.sv
hw_accel/hw_accel.v
hw_accel/hw_accel_axi4.v
hw_accel/hw_accel_nearest_neighbor_downscale.v
hw_accel/hw_accel_pack_rgb_gray.v
hw_accel/hw_accel_rgb2gray.v
hw_accel/hw_accel_wrapper.v
hw_accel/hw_accel_stream.v
tinyml/tinyml_accelerator.v
tinyml/tinyml_top.v
