`define TML_C1_AXI_DW	128
`define TML_C1_CONV_DEPTHW_MODE	"STANDARD"
`define TML_C1_CONV_DEPTHW_STD_IN_PARALLEL	16
`define TML_C1_CONV_DEPTHW_STD_OUT_PARALLEL	8
`define TML_C1_CONV_DEPTHW_STD_OUT_CH_FIFO_A	224
`define TML_C1_CONV_DEPTHW_STD_FILTER_FIFO_A	375
`define TML_C1_CONV_DEPTHW_STD_CNT_DTH	224
`define TML_C1_CONV_DEPTHW_LITE_PARALLEL	4
`define TML_C1_CONV_DEPTHW_LITE_AW	7
`define TML_C1_ADD_MODE	"STANDARD"
`define TML_C1_LR_MODE	"DISABLE"
`define TML_C1_FC_MODE	"DISABLE"
`define TML_C1_FC_MAX_IN_NODE	640
`define TML_C1_FC_MAX_OUT_NODE	640
`define TML_C1_MUL_MODE	"DISABLE"
`define TML_C1_MIN_MAX_MODE	"DISABLE"
`define TML_C1_TINYML_CACHE	"ENABLE"
`define TML_C1_CACHE_DEPTH	8192


