
# Efinity Interface Designer SDC
# Version: 2024.2.294.3.14
# Date: 2025-03-19 17:46

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: Ti180J484
# Project: tinyml_soc
# Timing Model: C4 (final)

# PLL Constraints
#################
create_clock -period 10.000 -name mipi_clk [get_ports {mipi_clk}]
create_clock -period 10.000 -name i_sys_clk [get_ports {i_sys_clk}]
create_clock -period 10.000 -name i_axi0_mem_clk [get_ports {i_axi0_mem_clk}]
create_clock -period 4.000 -name i_soc_clk [get_ports {i_soc_clk}]
create_clock -period 7.501 -name pll_ddr_CLKOUT0 [get_ports {pll_ddr_CLKOUT0}]

set_clock_groups -exclusive -group {i_soc_clk} -group {i_axi0_mem_clk} -group {jtag_inst1_TCK} -group {i_sys_clk} -group {mipi_clk}

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {io_jtag_tck}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {io_jtag_tck}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {io_jtag_tdi}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {io_jtag_tdi}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {io_jtag_tms}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {io_jtag_tms}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {system_uart_0_io_rxd}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {system_uart_0_io_rxd}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {io_jtag_tdo}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {io_jtag_tdo}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {system_uart_0_io_txd}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {system_uart_0_io_txd}]

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> -name jtag_inst1_TCK [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 1.387 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min 0.555 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.603 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.282 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 1.191 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.682 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.593 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.344 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.564 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.362 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.575 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.294 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 1.416 [get_ports {jtag_inst1_DRCK}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.884 [get_ports {jtag_inst1_DRCK}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> -name jtag_inst1_DRCK [get_ports {jtag_inst1_DRCK}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.626 [get_ports {jtag_inst1_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.332 [get_ports {jtag_inst1_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_inst1_TCK jtag_inst1_DRCK}

# DDR Constraints
#####################
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 3.675 [get_ports {ddr_inst_ARST_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.000 [get_ports {ddr_inst_ARST_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARADDR_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARADDR_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARAPCMD_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARAPCMD_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARBURST_0[1] ddr_inst_ARBURST_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARBURST_0[1] ddr_inst_ARBURST_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARID_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARID_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARLEN_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARLEN_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARSIZE_0[2] ddr_inst_ARSIZE_0[1] ddr_inst_ARSIZE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARSIZE_0[2] ddr_inst_ARSIZE_0[1] ddr_inst_ARSIZE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARVALID_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARVALID_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARLOCK_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARLOCK_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_ARQOS_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_ARQOS_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWADDR_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWADDR_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWAPCMD_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.350 [get_ports {ddr_inst_AWAPCMD_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWALLSTRB_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWALLSTRB_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWBURST_0[1] ddr_inst_AWBURST_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWBURST_0[1] ddr_inst_AWBURST_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWCOBUF_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWCOBUF_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWID_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWID_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWLEN_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWLEN_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWSIZE_0[2] ddr_inst_AWSIZE_0[1] ddr_inst_AWSIZE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWSIZE_0[2] ddr_inst_AWSIZE_0[1] ddr_inst_AWSIZE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWVALID_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWVALID_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWLOCK_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWLOCK_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWCACHE_0[3] ddr_inst_AWCACHE_0[2] ddr_inst_AWCACHE_0[1] ddr_inst_AWCACHE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWCACHE_0[3] ddr_inst_AWCACHE_0[2] ddr_inst_AWCACHE_0[1] ddr_inst_AWCACHE_0[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_AWQOS_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_AWQOS_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_BREADY_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_BREADY_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_RREADY_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_RREADY_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_WDATA_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_WDATA_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_WLAST_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_WLAST_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_WSTRB_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_WSTRB_0[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.310 [get_ports {ddr_inst_WVALID_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min -0.140 [get_ports {ddr_inst_WVALID_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_ARREADY_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_ARREADY_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.520 [get_ports {ddr_inst_AWREADY_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.680 [get_ports {ddr_inst_AWREADY_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.520 [get_ports {ddr_inst_BID_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.680 [get_ports {ddr_inst_BID_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_BRESP_0[1] ddr_inst_BRESP_0[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_BRESP_0[1] ddr_inst_BRESP_0[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_BVALID_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_BVALID_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_RDATA_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_RDATA_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_RID_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_RID_0[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_RLAST_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_RLAST_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_RRESP_0[1] ddr_inst_RRESP_0[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_RRESP_0[1] ddr_inst_RRESP_0[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_RVALID_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_RVALID_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -max 2.625 [get_ports {ddr_inst_WREADY_0}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~2~150}] -min 1.750 [get_ports {ddr_inst_WREADY_0}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 3.675 [get_ports {ddr_inst_ARST_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.000 [get_ports {ddr_inst_ARST_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARADDR_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARADDR_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARAPCMD_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARAPCMD_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARBURST_1[1] ddr_inst_ARBURST_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARBURST_1[1] ddr_inst_ARBURST_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARID_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARID_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARLEN_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARLEN_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARSIZE_1[2] ddr_inst_ARSIZE_1[1] ddr_inst_ARSIZE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARSIZE_1[2] ddr_inst_ARSIZE_1[1] ddr_inst_ARSIZE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARVALID_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARVALID_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARLOCK_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARLOCK_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_ARQOS_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_ARQOS_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWADDR_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWADDR_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWAPCMD_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.350 [get_ports {ddr_inst_AWAPCMD_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWALLSTRB_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWALLSTRB_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWBURST_1[1] ddr_inst_AWBURST_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWBURST_1[1] ddr_inst_AWBURST_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWCOBUF_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWCOBUF_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWID_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWID_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWLEN_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWLEN_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWSIZE_1[2] ddr_inst_AWSIZE_1[1] ddr_inst_AWSIZE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWSIZE_1[2] ddr_inst_AWSIZE_1[1] ddr_inst_AWSIZE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWVALID_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWVALID_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWLOCK_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWLOCK_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWCACHE_1[3] ddr_inst_AWCACHE_1[2] ddr_inst_AWCACHE_1[1] ddr_inst_AWCACHE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWCACHE_1[3] ddr_inst_AWCACHE_1[2] ddr_inst_AWCACHE_1[1] ddr_inst_AWCACHE_1[0]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_AWQOS_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_AWQOS_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_BREADY_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_BREADY_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_RREADY_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_RREADY_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_WDATA_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_WDATA_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_WLAST_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_WLAST_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_WSTRB_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_WSTRB_1[*]}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.310 [get_ports {ddr_inst_WVALID_1}]
set_output_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min -0.140 [get_ports {ddr_inst_WVALID_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_ARREADY_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_ARREADY_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.520 [get_ports {ddr_inst_AWREADY_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.680 [get_ports {ddr_inst_AWREADY_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.520 [get_ports {ddr_inst_BID_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.680 [get_ports {ddr_inst_BID_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_BRESP_1[1] ddr_inst_BRESP_1[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_BRESP_1[1] ddr_inst_BRESP_1[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_BVALID_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_BVALID_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_RDATA_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_RDATA_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_RID_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_RID_1[*]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_RLAST_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_RLAST_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_RRESP_1[1] ddr_inst_RRESP_1[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_RRESP_1[1] ddr_inst_RRESP_1[0]}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_RVALID_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_RVALID_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -max 2.625 [get_ports {ddr_inst_WREADY_1}]
set_input_delay -clock i_axi0_mem_clk -reference_pin [get_ports {i_axi0_mem_clk~CLKOUT~1~338}] -min 1.750 [get_ports {ddr_inst_WREADY_1}]

# HSIO GPIO Constraints
#########################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {i_osc1_ref_clk}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {i_osc1_ref_clk}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {i_sw[0]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {i_sw[0]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {i_sw[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {i_sw[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[2]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[2]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[4]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[4]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {o_led[5]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {o_led[5]}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~18~1}] -max 0.263 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~18~1}] -min -0.140 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~78~1}] -max 0.263 [get_ports {system_spi_0_io_ss}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~78~1}] -min -0.140 [get_ports {system_spi_0_io_ss}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~202~1}] -max 0.263 [get_ports {system_spi_1_io_sclk_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~202~1}] -min -0.140 [get_ports {system_spi_1_io_sclk_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~114~1}] -max 0.263 [get_ports {system_spi_1_io_ss}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~114~1}] -min -0.140 [get_ports {system_spi_1_io_ss}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~85~1}] -max 0.414 [get_ports {system_spi_0_io_data_0_read}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~85~1}] -min 0.276 [get_ports {system_spi_0_io_data_0_read}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~87~1}] -max 0.263 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~87~1}] -min -0.140 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~87~1}] -max 0.263 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~87~1}] -min -0.140 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~86~1}] -max 0.414 [get_ports {system_spi_0_io_data_1_read}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~86~1}] -min 0.276 [get_ports {system_spi_0_io_data_1_read}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~88~1}] -max 0.263 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~88~1}] -min -0.140 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~88~1}] -max 0.263 [get_ports {system_spi_0_io_data_1_writeEnable}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~88~1}] -min -0.140 [get_ports {system_spi_0_io_data_1_writeEnable}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~192~1}] -max 0.414 [get_ports {system_spi_1_io_data_0_read}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~192~1}] -min 0.276 [get_ports {system_spi_1_io_data_0_read}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~194~1}] -max 0.263 [get_ports {system_spi_1_io_data_0_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~194~1}] -min -0.140 [get_ports {system_spi_1_io_data_0_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~194~1}] -max 0.263 [get_ports {system_spi_1_io_data_0_writeEnable}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~194~1}] -min -0.140 [get_ports {system_spi_1_io_data_0_writeEnable}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~191~1}] -max 0.414 [get_ports {system_spi_1_io_data_1_read}]
set_input_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~191~1}] -min 0.276 [get_ports {system_spi_1_io_data_1_read}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~193~1}] -max 0.263 [get_ports {system_spi_1_io_data_1_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~193~1}] -min -0.140 [get_ports {system_spi_1_io_data_1_write}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~193~1}] -max 0.263 [get_ports {system_spi_1_io_data_1_writeEnable}]
set_output_delay -clock i_sys_clk -reference_pin [get_ports {i_sys_clk~CLKOUT~193~1}] -min -0.140 [get_ports {system_spi_1_io_data_1_writeEnable}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 0.828> [get_ports {mipi_clk}]
# set_clock_latency -source -hold <board_min + 0.552> [get_ports {mipi_clk}]
# set_clock_latency -source -setup <pll_clk_latency_mipi_clk_max + 2.386> [get_ports {i_sys_clk}]
# set_clock_latency -source -hold <pll_clk_latency_mipi_clk_min + 1.545> [get_ports {i_sys_clk}]
# set_clock_latency -source -setup <pll_clk_latency_mipi_clk_max + 2.386> [get_ports {i_axi0_mem_clk}]
# set_clock_latency -source -hold <pll_clk_latency_mipi_clk_min + 1.545> [get_ports {i_axi0_mem_clk}]
# set_clock_latency -source -setup <pll_clk_latency_mipi_clk_max + 2.386> [get_ports {i_soc_clk}]
# set_clock_latency -source -hold <pll_clk_latency_mipi_clk_min + 1.545> [get_ports {i_soc_clk}]
# set_clock_latency -source -setup <board_max + 1.907> [get_ports {pll_ddr_CLKOUT0}]
# set_clock_latency -source -hold <board_min + 1.271> [get_ports {pll_ddr_CLKOUT0}]
