RV_M=yes
#RV_C=yes
#RV_A=yes
#RV_F=yes
#RV_D=yes
#CFLAGS+=-DSMP
DEBUG?=yes
DEBUG_OG?=yes

CFLAGS += -DSYSTEM_UART_A_APB=SYSTEM_UART_0_IO_APB
CFLAGS += -DSYSTEM_GPIO_A_APB=SYSTEM_GPIO_0_IO_APB
CFLAGS += -DSYSTEM_I2C_A_APB=SYSTEM_I2C_0_IO_APB
